-- =====================================================================
-- POOM DB 스키마 (구 구현 기준본, 폐기)
--
-- 이 파일은 더 이상 유지되지 않는다.
-- 스키마의 기준본(canonical)은 docs/schema_v2.sql 하나다.
--
-- 과거에는 코드 모델(collabs / provider_id / credit_amount)과
-- 팀 확정 스키마 v2(projects / worker_id / agreed_credits)가 달라서
-- "구현 기준"과 "팀 확정" 두 계열의 DDL을 따로 두었다.
-- 이제 app/models.py가 docs/schema_v2.sql과 컬럼 단위로 1:1 일치하므로
-- 두 계열을 유지할 이유가 없다.
--
-- 로컬(SQLite)과 배포(PostgreSQL) 모두 테이블 생성은 app/db.py의
-- init_db() → Base.metadata.create_all() 이 담당한다. 이 파일을 직접 실행할 필요는 없다.
-- 사람이 읽는 DDL과 설계 근거 주석은 docs/schema_v2.sql을 본다.
-- =====================================================================
